baseURL = "/"
languageCode = "de-de"
title = "Planbar – Vorlagen, Rechner & Checklisten"
theme = "PaperMod"

[pagination]
  pagerSize = 10
  
[params]
  env = "production"
  defaultTheme = "light"
  description = "Deine faceless Factory für produktive Vorlagen, Rechner und Checklisten."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  blog = "/{{slug}}/"
  produkte = "/produkte/{{slug}}/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Haushalt & Finanzen"
  url  = "/blog/haushalt/"
  weight = 10

  [[menu.main]]
  name = "Job & Bewerbung"
  url  = "/blog/job/"
  weight = 20

  [[menu.main]]
  name = "Lernen & Alltag"
  url  = "/blog/lernen/"
  weight = 30

  [[menu.footer]]
  name = "Impressum"
  url  = "/impressum/"
  weight = 10

  [[menu.footer]]
  name = "Datenschutz"
  url  = "/datenschutz/"
  weight = 20

# force-deploy 2025-09-02T14:54:05
