baseURL = "/"
languageCode = "de-de"
title = "SmartWays – Vorlagen, Rechner & Checklisten"
theme = "PaperMod"

[pagination]
  pagerSize = 10
  
[params]
  env = "production"
  defaultTheme = "light"
  description = "Deine faceless Factory für produktive Vorlagen, Rechner und Checklisten."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  blog = "/{{slug}}/"
  produkte = "/produkte/{{slug}}/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"

[menu]

  # --- Hauptmenü (oben) ---
  [[menu.main]]
  name = "Haushalt & Finanzen"
  url  = "/blog/haushalt/"
  weight = 10
  identifier = "m-haushalt"

  [[menu.main]]
  name = "Job & Bewerbung"
  url  = "/blog/job/"
  weight = 20
  identifier = "m-job"

  [[menu.main]]
  name = "Lernen & Alltag"
  url  = "/blog/lernen/"
  weight = 30
  identifier = "m-lernen"

  [[menu.main]]
  name = "Shop"
  url  = "/produkte/"
  weight = 40

  # --- Dropdown unter Haushalt ---
  [[menu.main]]
  name = "Haushaltsbuch führen"
  url = "/haushaltsbuch-fuehren/"
  weight = 11
  parent = "m-haushalt"

  [[menu.main]]
  name = "Fixkosten-Liste"
  url = "/fixkosten-liste/"
  weight = 12
  parent = "m-haushalt"

  # --- Dropdown unter Job ---
  [[menu.main]]
  name = "Anschreiben-Generator"
  url = "/bewerbung-anschreiben-generator/"
  weight = 21
  parent = "m-job"

  [[menu.main]]
  name = "Anschreiben Quereinsteiger"
  url = "/anschreiben-quereinsteiger/"
  weight = 22
  parent = "m-job"

  # --- Dropdown unter Lernen ---
  [[menu.main]]
  name = "Lernplan erstellen"
  url = "/lernplan-erstellen/"
  weight = 31
  parent = "m-lernen"

  [[menu.main]]
  name = "Pomodoro-Vorlage"
  url = "/pomodoro-vorlage/"
  weight = 32
  parent = "m-lernen"

  # --- Footer ---
  [[menu.footer]]
  name = "Impressum"
  url  = "/impressum/"
  weight = 10

  [[menu.footer]]
  name = "Datenschutz"
  url  = "/datenschutz/"
  weight = 20



# force-deploy 2025-09-02T14:54:05
